#!/usr/bin/bash
if command -v zenity &> /dev/null; then
    dialog_helper=zenity
elif command -v kdialog &> /dev/null; then
    dialog_helper=kdialog
fi

if command -v /usr/sbin/prime-select &> /dev/null; then
    exit 0
elif command -v /usr/bin/prime-select &> /dev/null; then
    exit 0
elif command -v prime-select &> /dev/null; then
    exit 0
else
    case $@ in
        silent)
        ;;
        *)
            case $dialog_helper in
                zenity)
                    zenity --warning --title="Warning" --text="$(exec prime-i18n PrimeNotFound)"
                ;;
                kdialog)
                    kdialog --sorry "$(exec prime-i18n PrimeNotFound)" --title="PrimeRun"
                ;;
            esac
        ;;
    esac
    exit 1
fi