#!/usr/bin/bash
has_prime_select=false

($(exec prime-test))
case $? in
	0)
	has_prime_select=true
	;;
	1)
	;;
esac

if $has_prime_select; then
	current=($(exec /usr/sbin/prime-select get-current))
	driver=${current[2]}
	case $driver in
		intel)
			pkexec /usr/sbin/prime-select nvidia
			case $? in
				0)
				zenity --info --title="Logout" --text="$(exec prime-i18n Logout)"
				;;
			esac
		;;
		nvidia)
				pkexec /usr/sbin/prime-select intel
			case $? in
				0)
				zenity --info --title="Logout" --text="$(exec prime-i18n Logout)"
				;;
			esac
		;;
		offload)
			selected=$(zenity --list --radiolist --column="" --column="Title" --hide-header FALSE "nvidia" FALSE "intel" --hide-header --text="$(exec prime-i18n ToggleOffload)" --title="$(exec prime-i18n TitleSelect)")
			case $? in
				0)
				pkexec /usr/sbin/prime-select $selected
				case $? in
					0)
					zenity --info --title="$(exec prime-i18n TitleSuccess)" --text="$(prime-i18n Logout)."
					;;
				esac
				;;
			esac
		;;
	esac
	gnome-session-quit --logout
fi
