#!/usr/bin/bash
declare -A language_default
declare -A language_de

language_default["PrimeNotFound"]="prime-select could not be found. Abort"
language_de["PrimeNotFound"]="prime-select konnte nicht gefunden werden, breche ab."

language_default["Logout"]="Driver switched to nvidia, please log out."
language_de["Logout"]="Treiber gewechselt, bite melden Sie sich ab und wieder an"

language_default["BootDriver"]="Select driver to be used at boot"
language_de["BootDriver"]="Wählen Sie den Treiber, der beim Start des Systems benutzt werden soll"

language_default["TitleSelect"]="Select"
language_de["TitleSelect"]="Wählen Sie"

language_default["TitleSuccess"]="Success"
language_de["TitleSuccess"]="Erfolgreich"

language_default["BootDriverChanged"]="Driver changed successfully to:"
language_de["BootDriverChanged"]="Treiber erfolgreich geändert zu:"

IFS='.' read -ra lang <<< "$LANG"

case $lang in
    de_DE)
        echo ${language_de[$@]}
    ;;
    *)
        echo ${language_default[$@]}
    ;;
esac